name: Test and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.1"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t your-image:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hoanghy/e-tour:latest
          build-args: |
            NODE_ENV=${{ secrets.NODE_ENV }}
            PORT=${{ secrets.PORT }}
            CORS_URL=${{ secrets.CORS_URL }}
            LOG_DIR=${{ secrets.LOG_DIR }}
            MONGO_URL=${{ secrets.MONGO_URL }}
            TZ=${{ secrets.TZ }}
            DB_MIN_POOL_SIZE=${{ secrets.DB_MIN_POOL_SIZE }}
            DB_MAX_POOL_SIZE=${{ secrets.DB_MAX_POOL_SIZE }}
            ACCESS_TOKEN_VALIDITY_SEC=${{ secrets.ACCESS_TOKEN_VALIDITY_SEC }}
            REFRESH_TOKEN_VALIDITY_SEC=${{ secrets.REFRESH_TOKEN_VALIDITY_SEC }}
            TOKEN_ISSUER=${{ secrets.TOKEN_ISSUER }}
            TOKEN_AUDIENCE=${{ secrets.TOKEN_AUDIENCE }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
